name: copr-build
description: 'Build rpm packages in COPR for use in Fedora/RHEL based operating systems'

inputs:
  project-name:
    description: 'COPR Project Name'
    default: ${{ github.repository_owner }}
  package-name:
    description: 'Package name in COPR'
    default: ${{ github.event.repository.name }}
  git-remote:
    description: 'git remote URL'
    default: "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git"
  owner:
    description: 'COPR owner'
    default: ${{ github.repository_owner }}
  committish:
    description: "Comittish for COPR to track"
    default: "main"
  source-build-method:
    description: "COPR Source Build Method"
    default: "rpkg"

runs:
  using: composite
  steps:
    - name: build package in COPR
      id: calculate
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        ./copr-build \
          --source-build-method ${{ inputs.source-build-method }} \
          --owner ${{ inputs.owner }} \
          --committish ${{ inputs.committish }} \
          --git-remote ${{ inputs.git-remote }} \
          --project-name=${{ inputs.project-name }} \
          --package-name=${{ inputs.package-name }} >> $GITHUB_OUTPUT
